### PR TITLE
Big restructure

### PR DESCRIPTION
**Pull request by eiaro**
Please don't kill me... This is how I prefer to build libraries and it makes it easy to support multiple targets. It also make sense to have less files in the run-time package.

### CODE REVIEW

**Comment by nicolaiw** [comment]
Looks absolutely reasonable to me.

**Comment by Mr-Markus** [comment]
I like that structure and i can just agree with it.

I already tried to merge it locally and it works. But then we have the problem that the necessary Json Meta files can no longer be loaded and we need another solution or do you have already one?

And how would you reference the unpi? I saw that you have done the same work ther, too. This solution is also better, because of using Streams. As mentioned here https://github.com/Mr-Markus/ZigbeeNet/issues/6#issuecomment-430598329 it can now also be part of this repository. And if it is necessary to extract it to an own Project we can Export it or what ever.

What do you think?

**Comment by eiaro** [comment]
Did the JSON break? That wasn't intentional and it should be fixable by adjusting the path and setting them to copy I think. Didn't really think of them to be honest.

To speed up development I have included the UNPI files in CC on my local repository. I'm working on making it async and I have to go back and forth a lot, so it makes sense to me to have it close, at least for development. When project is done (stable), much of the CC code and UNPI can be taken out and prepared to be added the needed BLE code. This is by that point nothing more than refactorings.

The events on the SerialPort is notorious for being unreliable, so using the "hidden" Stream is the secret solution. It's better explained [here by Ben Voigt](http://www.sparxeng.com/blog/software/must-use-net-system-io-ports-serialport). Another benefit with this is if you get a TCP device or a high-speed USB device your code is already supporting streams.

Goal is to end with a ZigbeeNet that also can be used with TI, SiliconLabs and even other underlying stacks, right?

**Comment by Mr-Markus** [comment]
> Did the JSON break? That wasn't intentional and it should be fixable by adjusting the path and setting them to copy I think. Didn't really think of them to be honest.

The json files are still there, but they have to be included in the .csproj file in.netstandard projects. In other targets it can be different.
Something like this:

` <ItemGroup>
    <EmbeddedResource Include="Defs/zpi_meta.json" />
  </ItemGroup>`

> To speed up development I have included the UNPI files in CC on my local repository. I'm working on making it async and I have to go back and forth a lot, so it makes sense to me to have it close, at least for development. When project is done (stable), much of the CC code and UNPI can be taken out and prepared to be added the needed BLE code. This is by that point nothing more than refactorings.

Yes, i agree to choose this way. I already created a branch out of your pullrequest here. At the Moment it isn't running if you start the example Project, because of the broken json, which i would fix. I can merge it, if it doesn't make any Problems for you? And after that you should be able to create another pull request for your unpi implementation. Do you agree?

> Another benefit with this is if you get a TCP device or a high-speed USB device your code is already supporting streams

The CC2531 from Texas Instruments is an CC2530 chip an a board with FTDI and USB, but it should also be possible to communicate with the chip directly for example (Even if i don't now how at the Moment :-) )

> Goal is to end with a ZigbeeNet that also can be used with TI, SiliconLabs and even other underlying stacks, right?

Yes, exactly. It should be generic because the implementation of the ZigbeeAlliance specification should be the same inside all platforms and devices. So it is the best solution to seperate  ZCL (Zigbee Cluster Library) from stacks like Z-Stack / CC253x (Texas Instruments)

**Comment by eiaro** [comment]
> The json files are still there, but they have to be included in the .csproj file in.netstandard projects. In other targets it can be different.

Should be the same for all targets. Are you familiar with T4 as an alternative? Not sure it's a better solution, but it is an alternative being used in many cases and ensure type-safe operation.

> Yes, i agree to choose this way. I already created a branch out of your pullrequest here. At the Moment it isn't running if you start the example Project, because of the broken json, which i would fix. I can merge it, if it doesn't make any Problems for you? And after that you should be able to create another pull request for your unpi implementation. Do you agree?

Sure. It is still a work in progress, but I'll find a compile able moment. :)

> Yes, exactly. It should be generic because the implementation of the ZigbeeAlliance specification should be the same inside all platforms and devices. So it is the best solution to seperate ZCL (Zigbee Cluster Library) from stacks like Z-Stack / CC253x (Texas Instruments)

Exactly. Thinking a very abstract case the end user want to measure the temperature he would start the library and retrieve a list of nodes. From these nodes he would subscribe to updates on a specific endpoint / cluster. No need to worry about embedding the Zigbee commands into MT packages that need to be translated to Serial Packages.

**Comment by Mr-Markus** [comment]
> Should be the same for all targets. Are you familiar with T4 as an alternative? Not sure it's a better solution, but it is an alternative being used in many cases and ensure type-safe operation.

Yeah i know them and I would like to prefer generated code but I haven't worked with them yet... Maybe @nicolaiw can help?

> Sure. It is still a work in progress, but I'll find a compile able moment. :)

Ok, i merged your code. Greate work :-)

**Comment by nicolaiw** [comment]
I already used T4 templates yes.. I will have a look at it after the weekend (if the problem is not solved then :))

**Pull request merged**
